version: 0.0
os: linux

files:
  - source: index.html
    destination: /usr/share/nginx/html

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
      runas: root
